import { type ReactNode } from 'react';
import {
  SiReact, SiVuedotjs, SiThreedotjs, SiGreensock, SiTailwindcss,
  SiVite, SiVercel, SiFramer, SiJavascript, SiPhp, SiMysql,
  SiSymfony, SiOpengl, SiNextdotjs, SiNodedotjs, SiTypescript,
  SiFigma, SiGit, SiMongodb, SiExpress,
} from 'react-icons/si';
import {
  LuLayers, LuClapperboard, LuPalette, LuDatabase, LuGlobe,
  LuShieldCheck, LuLayoutGrid, LuBox, LuFileJson, LuMonitor,
  LuServer, LuWrench, LuUser, LuPenTool, LuMousePointer,
  LuImage, LuFilm, LuScissors, LuPaintbrush, LuSmartphone,
} from 'react-icons/lu';

const iconMap: Record<string, ReactNode> = {
  'react': <SiReact />,
  'vue.js': <SiVuedotjs />,
  'vue': <SiVuedotjs />,
  'symfony': <SiSymfony />,
  'tailwind': <SiTailwindcss />,
  'tailwindcss': <SiTailwindcss />,
  'mobile first': <LuSmartphone />,
  'three.js': <SiThreedotjs />,
  'react three fiber': <SiReact />,
  'r3f': <SiReact />,
  'gsap': <SiGreensock />,
  'tailwind css': <SiTailwindcss />,
  'vite': <SiVite />,
  'vercel': <SiVercel />,
  'framer motion': <SiFramer />,
  'javascript': <SiJavascript />,
  'glsl': <SiOpengl />,
  'glsl shaders': <SiOpengl />,
  'php': <SiPhp />,
  'sql': <SiMysql />,
  'json': <LuFileJson />,
  'zustand': <LuBox />,
  'parallax': <LuLayers />,
  'animation': <LuClapperboard />,
  'ui design': <LuPalette />,
  'base de données': <LuDatabase />,
  'site vitrine': <LuGlobe />,
  'mvc': <LuLayoutGrid />,
  'authentification': <LuShieldCheck />,
  'headless cms': <SiSymfony />,
  'next.js': <SiNextdotjs />,
  'node.js': <SiNodedotjs />,
  'typescript': <SiTypescript />,
  'figma': <SiFigma />,
  'adobe xd': <LuPenTool />,
  'photoshop': <LuImage />,
  'illustrator': <LuPaintbrush />,
  'after effects': <LuFilm />,
  'premiere pro': <LuScissors />,
  'reverse proxy': <LuServer />,
  'git': <SiGit />,
  'mongodb': <SiMongodb />,
  'express': <SiExpress />,
  'spline': <LuBox />,
  'framer': <SiFramer />,
  'front-end': <LuMonitor />,
  'back-end': <LuServer />,
  'outils': <LuWrench />,
  'développeur web full stack': <LuUser />,
  'ui/ux': <LuPenTool />,
  'prototypage': <LuMousePointer />,
  'ux research': <LuUser />,
};

export function getTechIcon(name: string): ReactNode | null {
  return iconMap[name.toLowerCase().trim()] ?? null;
}
